### ISSUE TITLE
Getting the script to use same path as in source

### ISSUE THREAD

**Issue by tanja84dk** [Digiex/M4V-Converter#11]
First of all thank you very much for the great script. I have great use of it in the work of converting my personal dvd rips with makemkv to smaller files for plex.

I would like to know if there is a way for the script to use same folder structure in the output as the files are in the input?

The reason is that my next project is to rip my dvd series boxes and is sorting the files right away and would like to be able to put the output directly in the plex servers folders with the same structure.

**Comment by xzKinGzxBuRnzx** [comment]
You should be able to accomplish this now! Update then any directory that occurs after the input will be maintained into the output!

Ex. /storage (input)
Ex. ~/ (output)
Result: /home/king/movies/a movie folder/a movie file.mp4

**Comment by tanja84dk** [comment]
Thank you very much for the quick response I will pull the updated source right away
