### ISSUE TITLE
Default it to keep 5.1 audio

### ISSUE THREAD

**Issue by tanja84dk** [Digiex/M4V-Converter#12]
I'm sorry to ask again but are there a way to get it to use 5.1 audio only if there is a 5.1 audio track and only use 2.0 audio if there isnt a 5.1 audio track?

**Comment by xzKinGzxBuRnzx** [comment]
As of now it currently takes a 5.1 stream and makes a AAC 2.0 stream for compatibility reasons.

If you enable dual-audio then you get AAC 2.0 (default stream) and AC3 5.1 stream.

Though AAC 2.0 is the default if your using Plex then most clients will auto select the AC3 5.1 stream if the device is capable of playing it.

From what I gather from this post you are  wanting the 5.1 stream only? If available in source file.

**Comment by tanja84dk** [comment]
Yes and the reason is because we do have surround at home and I have had issue some times with the dual stream because it then takes the comentary track because I always rip everything with makemkv to have the best as posible to start out from.

And also I think saving dual track is not the answer because then it takes more space in file size that we dont use here at home.

But again it were just if it were posible in he script.
And you dont have to change it just for me because if its okay then I will just look at the source myself and look if I'm able to change it to work.

Btw just as a side note and I hope its okay I say it. I'm actually using the script in docker and have atm got the build image down to 65 mb with all the requerements and still work perfectly

**Comment by xzKinGzxBuRnzx** [comment]
I will look into adding this soon! :)
