### ISSUE TITLE
Remuxing instead of encoding?

### ISSUE THREAD

**Issue by teflocarbon** [Digiex/M4V-Converter#13]
Hi there, thanks for your amazing effort in the script, works really well for converting.

However I want to just remux the files into a different container (mp4) instead of re-encoding the file to reduce file size, however I still want to convert the audio to AAC and use the dual to get both the original surround and AAC.

I cant find an option to avoid re-encoding however I know ffmpeg has a --codec option but this appears to be missing.
Any ideas?

**Comment by xzKinGzxBuRnzx** [comment]
You want to set video encoder, profile and level to “*”. This will cause it to accept both encoders (h264 or hevc) and copy the video!

Audio currently is limited to AAC 2.0 and AC3 5.1 (if available) when dual audio is enabled. Otherwise it’s only AAC 2.0. I do plan to change this soon to give more options. #12

**Comment by teflocarbon** [comment]
Thank you, much faster.
However is there an option to just convert audio and not even remux the video?
All my file formats are MKV and I just need to convert the audio.

**Comment by xzKinGzxBuRnzx** [comment]
I’m not sure I understand what your trying to accomplish.

If you want a new mp4 container by copying/remuxing the video. Then set encoder, profile and level to *. Also, enable dual audio.

In most cases this will result in converting only the audio and should only take a few minutes at most to complete, depending on PC specs.

**Comment by teflocarbon** [comment]
Apologies, I only want to covert the audio container and completely leave the video alone in it's original format (MKV) without remuxing it into MP4 sorry if that doesn't seem clear.

**Comment by xzKinGzxBuRnzx** [comment]
Currently that is not possible.

**Comment by teflocarbon** [comment]
All good, thank you.
