### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by snack32** [Digiex/M4V-Converter#15]
I'm trying to start the application via docke in a RPI 4r:

docker run -it --rm \
    -u 1001:100 \
    -v /mypath/to/process/xxx/:/input \
    digiex/mp4 -i /input -c /input/mp4.conf  

But I get the following error all the time:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/mp4/mp4.sh\": permission denied": unknown.

Thanks for your work and time.

**Comment by xzKinGzxBuRnzx** [comment]
This issue should be fixed!
