### ISSUE TITLE
bash: warning: shell level (1000) too high, resetting to 1

### ISSUE THREAD

**Issue by kalfun** [Digiex/M4V-Converter#16]
I'm on Unraid 6.8.3 and I have the NZBGet with the script installed in docker.

When I run the mp4.sh script, I get this error:

`bash: warning: shell level (1000) too high, resetting to 1`

I had to add ffmpeg and ffprobe to `/boot/config/go` file with the following command `cp /boot/ffmpeg-git/ffmpeg /usr/local/sbin` and `cp /boot/ffmpeg-git/ffprobe /usr/local/sbin`

Any idea what's wrong?

**Comment by xzKinGzxBuRnzx** [comment]
Can you try pulling the testing branch and see if that fixes the issue? `digiex/nzbget:testing` I've never tried unraid nor have the ability to test but I pushed a change that may fix the problem.

**Comment by kalfun** [comment]
Thanks for that. I was able to get passed the warning, but another error presented itself.

`It is NOT recommended that you run this script as root
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory
./mp4.sh: line 282: : No such file or directory`

Unfortunately, I have to run as root in shell for Unraid.

**Comment by xzKinGzxBuRnzx** [comment]
`It is NOT recommended that you run this script as root` This is just a warning, your using Docker so you can ignore it. `./mp4.sh: line 282: : No such file or directory` This is a bug, that should now be corrected. Please update and try again.

**Comment by kalfun** [comment]
Thanks for updating it. I ran the script and there weren't any errors in shell. However, when I run a test file in NZBGet, I get this error in the log:

INFO | Mon Nov 23 2020 16:32:08 | Post-process-script mp4/mp4.sh for [REDACTED] skipped
-- | -- | --
INFO | Mon Nov 23 2020 16:32:08 | mp4: PROFILE is incorrectly configured
INFO | Mon Nov 23 2020 16:32:08 | Executing post-process-script mp4/mp4.sh for [REDACTED]

In the `mp4.conf` file, this is what I have:

FORCE_SUBTITLES=true
OUTPUT=
AUDIO_CODEC=aac
AUDIO_BITRATE=128
PIXEL_FORMAT=yuv420p
VIDEO_BITRATE=source
**PROFILE=main**
LANGUAGES=eng
FAST=true
DIRECTORY_PERMISSION=0755
EXTENSION=mp4
PRESET=ultrafast
TUNE=film
VIDEO_CODEC=h264
FORCE_VIDEO=false
ENCODER=software
NORMALIZE=true
SUBTITLES=true
CRF=23
PROCESSES=ffmpeg
FORMAT=mp4
RESOLUTION=source
BACKGROUND=false
MEDIAINFO=/usr/bin/mediainfo
FORCE_AUDIO=false
DEBUG=false
DUAL_AUDIO=false
DELETE=true
FFMPEG=/usr/local/sbin/ffmpeg
INPUT=
LEVEL=4.0
FILE=mp4.conf
FFPROBE=/usr/local/sbin/ffprobe
FORCE_LEVEL=false
VERBOSE=true
AUDIO_CHANNELS=2
THREADS=6
FILE_PERMISSION=0644




**EDIT: Seems like it's working now. I changed PROFILE inside NZBGet from `*` to `main` and it works. But now I'm not able to use `*` and let x264 decide which profile to use**

**Comment by xzKinGzxBuRnzx** [comment]
I changed all of the variables from accepting `*`, instead use `source` which will do the same thing as `*` would of.
