### ISSUE TITLE
NZBGET in docker container

### ISSUE THREAD

**Issue by ghost** [Digiex/M4V-Converter#4]
HI,

i've installed FFMPEG on my main system but i think because of running NZBGET in a docker container m2v script doenst see the ffmpeg installed on the main system.

Can you help ?

ps.

Thank you for this great script.

**Comment by xzKinGzxBuRnzx** [comment]
This would happen due to how docker works. You need to install ffmpeg on the nzbget container. You can do so by...

docker exec -it nzbget /bin/bash

If you need anymore help then let me know.

**Comment by ghost** [comment]
Yes i tought so, but i was unable to install ffmpeg in the nzbget container.

I was trying to map the ffmpeg binary inside the docker container and tried to change the script to look for mycomputer/ffmpeg but this doenst seem to work.

Can i change the location of ffmpeg anywhere in the script ?

**Comment by xzKinGzxBuRnzx** [comment]
Currently there is no option to specify a location to the ffmpeg binary. Did you try using the provided install_ffmpeg.sh script?

**Comment by ghost** [comment]
Yes i've tried that. But somehow execution of a shell script wont start in a docker container.

Tried to chmod + x also no effect...i think its missing librarys that are stripped out of the linuxserver.io nzbget container.

**Comment by xzKinGzxBuRnzx** [comment]
I added the ability to specify a location to ffmpeg binary but in your case, I'm not sure this will help. I need to experiment with docker and come up with a solution.

**Comment by xzKinGzxBuRnzx** [comment]
I've created a Dockerfile that will install NZBGet, FFmpeg and M4V-Converter script. It is based on linuxserver/nzbget and jrottenberg/ffmpeg

I've put it into a new testing branch for now as I'm not sure if I've done everything correctly and I still need to test the script further.

However, If you want to give it a go then it should be as simple as docker pull xzkingzxburnzx/m4v-converter:testing

Create a container by running docker create --name nzbget -p 6789:6789 -e PUID=1000 -e PGID=1000 -e TZ=America/New_York -v /path/to/config:/config -v /path/to/downloads:/downloads xzkingzxburnzx/m4v-converter:testing

**Comment by ghost** [comment]
Oke, i will try this, thanks!

**Comment by xzKinGzxBuRnzx** [comment]
Just so you know, I've updated the docker tag to nzbget.
xzkingzxburnzx/m4v-converter:nzbget

You should remove and recreate the container if you used the previous testing tag/branch.

**Comment by ghost** [comment]
This works great, thanks!

**Comment by ghost** [comment]
When will you update this image to v20 of nzbget ?

**Comment by xzKinGzxBuRnzx** [comment]
@doludizgin I wasn't aware it had not updated automatically, I had it set to. I think recent build attempts failed due to nasm.us website being down. Anyways, I've updated the Dockerfile to build directly from jrottenberg/ffmpeg and have triggered the build manually. Update and you'll have v20!

**Comment by ghost** [comment]
@xzKinGzxBuRnzx Thank you, i've updated the image!

**Comment by ghost** [comment]
@xzKinGzxBuRnzx I am getting this error on the latstest docker image:


M4V-Converter: While you do have FFmpeg installed, it has been compiled with the "--enable-small" option and this will cause issues. Please reinstall without this option
--

**Comment by xzKinGzxBuRnzx** [comment]
@doludizgin Forgot about that. I’ve removed it, update to fix!
