### ISSUE TITLE
Show ETA converting time or progress bar in NZBGET - Feature

### ISSUE THREAD

**Issue by ghost** [Digiex/M4V-Converter#7]
Hi,

Just wondering if this is at all to get an ETA from ffmpeg and push back this data in nzbget.

So you can see an ETA maybe with graphical bar.

**Comment by xzKinGzxBuRnzx** [comment]
Percentage and ETA is displayed when you enable verbose mode. This functionality is limited to verbose mode due to how spammy it can become.
