### ISSUE TITLE
level 4.1 creates level 3.1 files

### ISSUE THREAD

**Issue by ghost** [Digiex/M4V-Converter#8]
I've noticed that recently my files are getting 3.1 level instead of the selected 4.1 after converting.

**Comment by xzKinGzxBuRnzx** [comment]
This is happening cause the source file is 3.1, which can target more devices than a higher setting such as 4.1. Setting 4.1 (which is the default) allows files less than 4.1 and greater/equal to 3.0.

I’ve added option “Force Level” which if set to true will force it to 4.1 if that is what you prefer.

**Comment by ghost** [comment]
Ah, thanks.

Got it
